### ISSUE TITLE
Why lrmes = 1 - exp(log(1 - d) .* beta_x);

### ISSUE THREAD

**Issue by TigerZhao007** [TommasoBelluzzo/SystemicRisk#2]
Hi, Tommaso,
Thank you for sharing your code. 
In SystemicRisk/ScriptsProbabilistic/calculate_mes.m,
I noticed that you have changed the 
lrmes = 1 - exp(-18 .* mes);
to
lrmes = 1 - exp(log(1 - d) .* beta_x);
Why? 
Is there any literature supporting this ?
I am So confusing.
Thanks a lot.

Best,
Andy

**Comment by TigerZhao007** [comment]
I noticed from:
https://vlab.stern.nyu.edu/doc/16?topic=mdls
"Specifically, it is calculated as 1-exp(log(1-d)*beta)"
But, Why?

**Comment by TommasoBelluzzo** [comment]
Hi Andy, Tiger, thanks for your feedback!

The algorithm has been modified in order to take into account the last proposed methodology of SRISK calculation. The LRMES computation has been revised a few years ago and the old approximation **1 - exp(-18 * mes)** has been replaced with **1 - exp(log(1 - d) * beta)**.

This update is directly taken from the V-Lab documentation, which is a project created and supervised by Rob Engle (the author of the SRISK measure). For a non-comprehensive reference of the methodology, you can visit the following link:

https://vlab.stern.nyu.edu/doc/17?topic=mdls

**Comment by TigerZhao007** [comment]
Assume that
d=0.40
beta=0.90
Then
LRMES=1 - exp(log(1 - d) * beta)=0.3686

Why LRMES is a positive number?
LRMES should be  negative.
