### ISSUE TITLE
Dataset question

### ISSUE THREAD

**Issue by wangyazhao001** [TommasoBelluzzo/SystemicRisk#3]
Hello!  In the Example_Large.xlsx of Datasets,there is "Separate Accounts".Can you tell me what the "Separate Accounts" is?Thank you very much!

**Comment by TommasoBelluzzo** [comment]
I introduced separate accounts because insurance companies (signally, life insurers) usually accumulate their premiums in investment funds. Those invested premiums are normally registered as both assets and liabilities in balance sheets, therefore a fluctuation in their values does not affect the book equity, only the overall balance volume.

If separate accounts are included in the dataset, the DEBT component of SRISK is reduced so that only s% of liabilities due to separate accounts are included in order to avoid overstating the capital requirements.

**Comment by wangyazhao001** [comment]
> I introduced separate accounts because insurance companies (signally, life insurers) usually accumulate their premiums in investment funds subject to explicit guarantees of return and withdrawal penalties. Those invested premiums are normally registered as both assets and liabilities in balance sheets, therefore a fluctuation in their values does not affect the book equity, only the overall balance volume.
> 
> If separate accounts are included in the dataset, the DEBT component of SRISK is reduced so that only x% of liabilities due to separate accounts are included in order to avoid overstating the capital requirements. On the top of that, lowering their contribution to the DEBT component serves as a good workaround for keeping the desired capital ratios.

Thank you very much! Another question! If I want to calaulate Spillover without separate accounts because I don't have these datas, should I change  some codes？
